# Enables & disables spacing between go statements.
# E.g. {{ statement }} vs {{statement}}.
# Default: true
goTemplateBracketSpacing = true

[[overrides]]
files = ["*.html"]

[overrides.options]
parser = "go-template"
tabWidth = 4
printWidth = 120
