version: 2.1
jobs:
  build-check:
    docker:
      - image: cibuilds/hugo:0.92
    working_directory: ~/get-started-it
    steps:
      - checkout
      - run:
          name: 'Hugo Build'
          command: HUGO_ENV=production hugo -v -s exampleSite
      - run:
          name: 'Test Website'
          command: htmlproofer exampleSite/public --check-html --allow-hash-href --empty-alt-ignore --disable-external

workflows:
  build-check-exampleSite:
    jobs:
      - build-check
